version: '3'
services:
#database
  mysql_host:
    image: mysql:5.7  
    container_name: mysql_host
    volumes:
      - ".mysql-data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"    
    networks: 
      - local-net
#php host
  apache:
    build: .
    container_name: apache_host
    restart: always
    volumes:
      #root dir
      - ./:/var/www/html/:rw
      #config dir
      - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
      - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
    ports:
      - "81:80"
    depends_on:
      - mysql_host
    # environment:
    # - VIRTUAL_HOST=shop.dev
    networks: 
      - local-net
      
#phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql_host
    image: phpmyadmin/phpmyadmin:latest 
    environment:
      PMA_HOST: mysql_host
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks: 
      - local-net
networks:
  local-net:
    driver: bridge
volumes:
  .mysql-data: